# Generated by Django 3.2.25 on 2024-12-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipeline',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='name',
        ),
        migrations.AddField(
            model_name='pipeline',
            name='diameter',
            field=models.FloatField(default=0, verbose_name='Diameter (mm)'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='length',
            field=models.FloatField(default=0, verbose_name='Length (m)'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='material',
            field=models.CharField(default=0, max_length=100, verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('under_maintenance', 'Under Maintenance')], default='active', max_length=20, verbose_name='Status'),
        ),
    ]
