# Generated by Django 3.2.25 on 2024-12-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20241214_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startPoint', models.CharField(max_length=100, verbose_name='Start Point')),
                ('endPoint', models.CharField(max_length=100, verbose_name='End Point')),
                ('volume', models.FloatField(verbose_name='Volume (m³)')),
                ('productType', models.CharField(max_length=100, verbose_name='Product Type')),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='System Name')),
                ('startDate', models.DateField(verbose_name='Start Date')),
                ('endDate', models.DateField(verbose_name='End Date')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance')], default='inactive', max_length=20, verbose_name='Status')),
            ],
        ),
    ]
